CRM/clientes/urls.py
from django.urls import include, path

from . import views

app_name = "clientes"

urlpatterns = [
    path(
        "criar/",
        views.criar_clientes,
        name="criar_cliente",
    ),
    path(
        "<slug:slug>/",
        include(
            [
                path(
                    "",
                    views.ver_cliente,
                    name="ver_cliente",
                ),
                path(
                    "atualizar/",
                    views.atualizar_cliente,
                    name="atualizar_cliente",
                ),
                path(
                    "enderecos/",
                    include("CRM.enderecos.urls", namespace="enderecos"),
                ),
            ],
        ),
    ),
    path(
        "servico/<str:tipo_servico>/",
        views.listar_clientes,
        name="listar_clientes_por_tipo_servico",
    ),
    path(
        "",
        views.listar_clientes,
        name="listar_clientes",
    ),
]

CRM/urls.py
from django.urls import path

from . import views

app_name = "crm"

urlpatterns = [
    path("", views.ir_para_lista_clientes, name="ir_para_lista_clientes"),
]

config/urls.py
"""
URL configuration for config project.
"""

from debug_toolbar.toolbar import debug_toolbar_urls  # noqa: I001
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("gelias.urls", namespace="gelias")),
    path("clientes/", include("gelias.clientes.urls", namespace="clientes")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += (
        static(settings.STATIC_URL, documents_root=settings.STATIC_ROOT)
        + debug_toolbar_urls()
    )

gelias/clientes/urls.py
from django.urls import path

from . import views

app_name = "clientes"

urlpatterns = [
    path("", views.Index.as_view(), name="index"),
]

CRM/clientes/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _


class Cliente(models.Model):
    class TipoCliente(models.TextChoices):
        PF = "PF", _("Pessoa Física")
        PJ = "PJ", _("Pessoa Jurídica")

    criado_em = models.DateTimeField(_("Criado em"), auto_now_add=True)
    atualizado_em = models.DateTimeField(_("Atualizado em"), auto_now=True)
    nome = models.CharField(_("Nome"), max_length=255, unique=True)
    slug = models.SlugField(_("Slug"), unique=True, max_length=255)
    tipo_cliente = models.CharField(
        _("Tipo de Cliente"),
        max_length=2,
        choices=TipoCliente.choices,
        default=TipoCliente.PF,
    )
    observacoes = models.TextField(_("Observações"), blank=True)
    ativo = models.BooleanField(
        _("Ativo"),
        help_text=_("Desmarque essa opção caso o cliente cancele o serviço."),
        default=True,
    )
    alarme = models.BooleanField(
        _("Alarme"),
        help_text=_(
            "Marque essa opção caso o serviço de monitoramento por alarme tenha sido contratado."
        ),
        default=False,
    )
    camera = models.BooleanField(
        _("Câmera"),
        help_text=_(
            "Marque essa opção caso o serviço de monitoramento por câmeras tenha sido contratado."
        ),
        default=False,
    )

    @property
    def listar_enderecos(self):
        return self.enderecos.all()

    class Meta:
        verbose_name = _("Cliente")
        verbose_name_plural = _("Clientes")
        ordering = [
            "nome",
            "ativo",
        ]
        indexes = [models.Index(fields=["nome"], name="idx_cliente_nome")]

    def __str__(self):
        return self.nome

    def atualizar_cliente(self):
        return reverse("clientes:atualizar_cliente", kwargs={"slug": self.slug})

    def ver_cliente(self):
        return reverse("clientes:ver_cliente", kwargs={"slug": self.slug})

    def criar_cliente(self):
        """
        Retorna a URL para criar um novo cliente, com o parâmetro de referência do cliente atual.
        """
        return f"{reverse('clientes:criar_cliente')}?from_cliente={self.slug}"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.nome)
        super().save(*args, **kwargs)


# class Dvr(models.Model):
#     criado_em = models.DateTimeField(_("Criado em"), auto_now_add=True)
#     atualizado_em = models.DateTimeField(_("Atualizado em"), auto_now=True)
#     cliente = models.ForeignKey(
#         "clientes.Cliente",
#         verbose_name=_("Cliente"),
#         on_delete=models.CASCADE,
#         related_name="DVR",
#     )
#     fabricante = models.CharField(_("Fabricante"), max_length=32, blank=True)
#     modelo = models.CharField(_("Modelo"), max_length=32, blank=True)
#     serial = models.CharField(_("Serial"), max_length=64, blank=True)
#     ip = models.CharField(_("IP"), max_length=32, blank=True)
#     porta = models.CharField(_("Porta"), max_length=10, blank=True)
#     usuario = models.CharField(_("Usuário"), max_length=64, blank=True)
#     senha = models.CharField(_("Senha"), max_length=255, blank=True)

#     class Meta:
#         verbose_name = _("DVR")
#         verbose_name_plural = _("DVR")
#         ordering = [
#             "fabricante",
#             "modelo",
#         ]


# class CentralAlarme(models.Model):
#     criado_em = models.DateTimeField(_("Criado em"), auto_now_add=True)
#     atualizado_em = models.DateTimeField(_("Atualizado em"), auto_now=True)
#     cliente = models.ForeignKey(
#         "clientes.Cliente",
#         verbose_name=_("Cliente"),
#         on_delete=models.CASCADE,
#         related_name="centrais_de_alarmes",
#     )
#     mac = models.CharField(_("MAC"), max_length=64, blank=True)
#     usuario = models.CharField(_("Usuário"), max_length=64, blank=True)
#     senha = models.CharField(_("Senha"), max_length=255, blank=True)

#     class Meta:
#         verbose_name = _("Central de Alarme")
#         verbose_name_plural = _("Centrais de Alarmes")
#         ordering = [
#             "mac",
#         ]

CRM/clientes/forms.py
from django import forms

from .models import Cliente


class FormulárioBase(forms.ModelForm):
    """Base para formulários de cliente."""

    class Meta:
        model = Cliente
        fields = (
            "nome",
            "tipo_cliente",
            "alarme",
            "camera",
            "ativo",
            "observacoes",
        )


class FormularioCriarCliente(FormulárioBase):
    """Formulário para criar um novo cliente."""

    pass


class FormularioAtualizarCliente(FormulárioBase):
    """Formulário para atualizar um cliente existente."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in ["nome", "tipo_cliente"]:
            self.fields[field].widget.attrs["readonly"] = "readonly"


class FormularioVerCliente(FormulárioBase):
    """Formulário para visualizar os detalhes de um cliente."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs["disabled"] = "disabled"

CRM/clientes/views.py
from django.views import generic

from . import forms
from .models import Cliente


class CriarClientes(generic.CreateView):
    """View para criar clientes."""

    form_class = forms.FormularioCriarCliente
    template_name = "clientes/criar_cliente.html"

    def get_success_url(self):
        return self.object.ver_cliente()

    def get_context_data(self, **kwargs):
        cliente_anterior = self.request.GET.get("from_cliente")

        if cliente_anterior and "cliente_anterior" not in kwargs:
            kwargs["cliente_anterior"] = cliente_anterior

        return super().get_context_data(**kwargs)


criar_clientes = CriarClientes.as_view()


class ListarClientes(generic.ListView):
    """View para listar clientes."""

    template_name = "clientes/listar_clientes.html"
    queryset = Cliente.objects.all().only(
        "nome", "tipo_cliente", "alarme", "camera", "ativo"
    )
    context_object_name = "clientes"
    paginate_by = 50

    def get_queryset(self):
        self.tipo_servico = self.kwargs.get("tipo_servico")

        if self.tipo_servico == "alarme":
            self.queryset = self.queryset.filter(alarme=True)
        elif self.tipo_servico == "camera":
            self.queryset = self.queryset.filter(camera=True)

        return super().get_queryset()

    def get_context_data(self, **kwargs):
        if "tipo_servico" not in kwargs:
            kwargs["tipo_servico"] = self.tipo_servico
        return super().get_context_data(**kwargs)


listar_clientes = ListarClientes.as_view()


class VerCliente(generic.DetailView):
    """View para ver detalhes do cliente."""

    template_name = "clientes/ver_cliente.html"
    model = Cliente
    context_object_name = "cliente"

    def get_context_data(self, **kwargs):
        self.extra_context = {
            "dados": forms.FormularioVerCliente(instance=self.get_object()),
        }
        return super().get_context_data(**kwargs)


ver_cliente = VerCliente.as_view()


class AtualizarCliente(generic.UpdateView):
    """View para atualizar cliente."""

    template_name = "clientes/atualizar_cliente.html"
    form_class = forms.FormularioAtualizarCliente
    model = Cliente

    def get_success_url(self):
        return self.object.ver_cliente()


atualizar_cliente = AtualizarCliente.as_view()

gelias/clientes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class Index(LoginRequiredMixin, TemplateView):
    extra_context = {"pagina": "clientes"}
    template_name = "clientes/index.html"

CRM/clientes/templates/clientes/atualizar_cliente.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    {{ cliente.nome }}
{% endblock title %}
{% block content %}
    <header class="d-flex align-center justify-content-between border-bottom mb-3 pb-2">
        <h3>{{ cliente.nome }}</h3>
        <nav>
            <a href="{% url 'clientes:listar_clientes' %}"
               class="btn btn-outline-secondary">
                <i class="bi bi-chevron-double-left"></i>
            </a>
            <a href="{{ cliente.ver_cliente }}" class="btn btn-outline-secondary">
                <i class="bi bi-chevron-left"></i>
            </a>
            <a href="{{ cliente.criar_cliente }}" class="btn btn-outline-secondary">
                <i class="bi bi-plus"></i>
            </a>
        </nav>
    </header>
    <main class="card card-body mb-3">
        <form action="{{ request.path }}" method="post">
            {% csrf_token %}
            <header class="d-flex justify-content-between align-items-center border-bottom mb-3 pb-2">
                <h6 class="">Geral</h6>
                <button class="btn btn-outline-secondary" type="submit">
                    <i class="bi bi-pencil"></i>
                    Atualizar
                </button>
            </header>
            <main class="row">
                <section class="col-6">
                    {{ form.nome|as_crispy_field }}
                    {{ form.tipo_cliente|as_crispy_field }}
                    {{ form.alarme|as_crispy_field }}
                    {{ form.camera|as_crispy_field }}
                </section>
                <section class="col-6">
                    {{ form.observacoes|as_crispy_field }}
                </section>
            </main>
            <footer class="col-12 border-top mt-3 pt-2">
                {{ form.ativo|as_crispy_field }}
            </footer>
        </form>
    </main>
{% endblock content %}
O campo "ativo" do mei model de cliente tem o valor padrão como True,

CRM/clientes/templates/clientes/criar_cliente.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Criar Cliente
{% endblock title %}
{% block content %}
    <header class="d-flex align-center justify-content-between border-bottom mb-3 pb-2">
        <h3>Criar Cliente</h3>
        {% if cliente_anterior %}
            <div>
                <a href="{% url 'clientes:listar_clientes' %}"
                   class="btn btn-outline-secondary">
                    <i class="bi bi-chevron-double-left"></i>
                </a>
                <a href="{% url 'clientes:ver_cliente' slug=cliente_anterior %}"
                   class="btn btn-outline-secondary">
                    <i class="bi bi-chevron-left"></i>
                </a>
            </div>
        {% else %}
            <a href="{% url 'clientes:listar_clientes' %}"
               class="btn btn-outline-secondary">
                <i class="bi bi-chevron-left"></i>
            </a>
        {% endif %}
    </header>
    <main class="card card-body mb-3">
        <form action="{{ request.path }}" method="post">
            {% csrf_token %}
            <header class="d-flex justify-content-between align-items-center border-bottom mb-3 pb-2">
                <h6 class="">Geral</h6>
                <button class="btn btn-outline-secondary" type="submit">
                    <i class="bi bi-plus"></i>
                    Criar
                </button>
            </header>
            <main class="row">
                <section class="col-6">
                    {{ form.nome|as_crispy_field }}
                    {{ form.tipo_cliente|as_crispy_field }}
                    {{ form.alarme|as_crispy_field }}
                    {{ form.camera|as_crispy_field }}
                </section>
                <section class="col-6">
                    {{ form.observacoes|as_crispy_field }}
                </section>
            </main>
            <footer class="col-12 border-top mt-3 pt-2">
                {{ form.ativo|as_crispy_field }}
            </footer>
        </form>
    </main>
{% endblock content %}

CRM/clientes/templates/clientes/listar_clientes.html
{% extends 'base.html' %}

{% block title %}
    Listagem de todos os Clientes
{% endblock title %}
{% block content %}
    <header class="d-flex align-center justify-content-between border-bottom mb-3 pb-2">
        <h3>Listar Clientes</h3>
        <a href="{% url 'clientes:criar_cliente' %}"
           class="btn btn-outline-secondary">
            <i class="bi bi-plus"></i>
        </a>
    </header>
    {% if clientes %}
        <main class="card card-body">
            <nav class="nav nav-underline mb-3">
                <a href="{% url 'clientes:listar_clientes' %}"
                   class="nav-link text-secondary {% if not tipo_servico %}active{% endif %}"
                   {% if not tipo_servico %}aria-current="page"{% endif %}>Todos</a>
                <a href="{% url 'clientes:listar_clientes_por_tipo_servico' tipo_servico='alarme' %}"
                   class="nav-link text-secondary {% if tipo_servico == 'alarme' %}active{% endif %}"
                   {% if tipo_servico == 'alarme' %}aria-current="page"{% endif %}>Alarme</a>
                <a href="{% url 'clientes:listar_clientes_por_tipo_servico' tipo_servico='camera' %}"
                   class="nav-link text-secondary {% if tipo_servico == 'camera' %}active{% endif %}"
                   {% if tipo_servico == 'camera' %}aria-current="page"{% endif %}>Câmera</a>
            </nav>
            {% for cliente in clientes %}
                <section class="{% if not forloop.last %}border-bottom mb-3{% endif %}">
                    <p>
                        <a class="{% if cliente.ativo %}link-dark{% else %}text-body-tertiary{% endif %} link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover"
                           href="{{ cliente.ver_cliente }}">{{ cliente.nome }}</a> <span class="badge rounded-pill {% if cliente.ativo %}text-bg-secondary{% else %}text-bg-secondary{% endif %}">{{ cliente.tipo_cliente }}</span>
                    </p>
                    <p>
                        {% if cliente.alarme %}<span class="badge text-bg-secondary">Alarme</span>{% endif %}
                        {% if cliente.camera %}<span class="badge text-bg-secondary">Camera</span>{% endif %}
                    </p>
                </section>
            {% endfor %}
        </main>
    {% else %}
        <p>
            Num cliente foi cadastrado ainda.
            <a class="link-dark link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover"
               href="{% url 'clientes:criar_cliente' %}">Cadastre o primeiro</a>
        </p>
    {% endif %}
{% endblock content %}

CRM/clientes/templates/clientes/remover_cliente.html
{% extends 'base.html' %}

{% block title %}
    remover_cliente
{% endblock title %}
{% block content %}
    <h1>remover_cliente</h1>
{% endblock content %}

CRM/clientes/templates/clientes/ver_cliente.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    {{ cliente.nome }}
{% endblock title %}
{% block content %}
    <header class="d-flex align-center justify-content-between border-bottom mb-3 pb-2">
        <h3>{{ cliente.nome }}</h3>
        <nav>
            <a href="{% url 'clientes:listar_clientes' %}"
               class="btn btn-outline-secondary">
                <i class="bi bi-chevron-left"></i>
            </a>
            <a href="{{ cliente.criar_cliente }}" class="btn btn-outline-secondary">
                <i class="bi bi-plus"></i>
            </a>
        </nav>
    </header>
    <section class="card card-body mb-3">
        <header class="d-flex justify-content-between align-items-center border-bottom mb-3 pb-2">
            <h6 class="">Geral</h6>
            <a href="{{ cliente.atualizar_cliente }}"
               class="btn btn-outline-secondary"><i class="bi bi-pencil"></i></a>
        </header>
        <main class="row">
            <section class="col-6">
                {{ dados.nome|as_crispy_field }}
                {{ dados.tipo_cliente|as_crispy_field }}
                {{ dados.alarme|as_crispy_field }}
                {{ dados.camera|as_crispy_field }}
            </section>
            <section class="col-6">
                {{ dados.observacoes|as_crispy_field }}
            </section>
        </main>
        <footer class="col-12 border-top mt-3 pt-2">
            {{ dados.ativo|as_crispy_field }}
        </footer>
    </section>
    <section class="card card-body mb-3">
        <header class="d-flex justify-content-between align-items-center border-bottom mb-3 pb-2">
            <h6>Endereços</h6>
            <a href="{% url 'clientes:enderecos:criar_endereco' cliente.slug %}"
               class="btn btn-outline-secondary"><i class="bi bi-plus"></i></a>
        </header>
        <main>
            {% for endereco in cliente.listar_enderecos %}
                <section class="mb-3">
                    <input type="text"
                           name="endereco-{{ forloop.count }}"
                           value="{{ endereco }}"
                           maxlength="255"
                           disabled="disabled"
                           class="textinput form-control"
                           required=""
                           id="id_endereco-{{ forloop.counter }}" />
                </section>
            {% empty %}
                <p>
                    Nenhum endereço foi cadastrado ainda.
                    <a class="link-dark link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover"
                       href="{% url "clientes:enderecos:criar_endereco" cliente.slug %}">Cadastre o primeiro</a>
                </p>
            {% endfor %}
        </main>
    </section>
{% endblock content %}