CRM/urls.py
from django.urls import path

from . import views

app_name = "crm"

urlpatterns = [
    path("", views.ir_para_lista_clientes, name="ir_para_lista_clientes"),
]

config/urls.py
"""
URL configuration for config project.
"""

from debug_toolbar.toolbar import debug_toolbar_urls  # noqa: I001
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("gelias.urls", namespace="gelias")),
    path("clientes/", include("gelias.clientes.urls", namespace="clientes")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += (
        static(settings.STATIC_URL, documents_root=settings.STATIC_ROOT)
        + debug_toolbar_urls()
    )

gelias/clientes/urls.py
from django.urls import path

from . import views

app_name = "clientes"

urlpatterns = [
    path("", views.Index.as_view(), name="index"),
]

gelias/urls.py
from django.urls import path

from . import views

app_name = "gelias"

urlpatterns = [
    path("", views.Index.as_view(), name="index"),
]

gelias/clientes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class Index(LoginRequiredMixin, TemplateView):
    extra_context = {"pagina": "clientes"}
    template_name = "clientes/index.html"

gelias/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class Index(LoginRequiredMixin, TemplateView):
    template_name = "gelias/index.html"

gelias/templates/_base.html
<!DOCTYPE html>
{% load i18n static %}

<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Gelias / {% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap\dist\css\bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-icons\font\bootstrap-icons.css' %}">
    <script defer src="{% static '@popperjs\core\dist\umd\popper.js' %}"></script>
    <script defer src="{% static 'bootstrap\dist\js\bootstrap.js' %}"></script>
  </head>

  <body class="bg-secondary-subtle">
    {% block navmenu %}
    <header class="mb-5 py-3 border-0 shadow-lg bg-white">
      <div class="container-xxl">
        <div class="d-flex align-items-center justify-content-between">
          <section class="d-flex gap-2 align-items-center">
            <button class="d-lg-none btn btn-outline-secondary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
              <i class="bi bi-list"></i>
            </button>
            <a href="{% url "gelias:index" %}" class="fs-3 link-body-emphasis link-offset-2 link-underline-opacity-25 link-underline-opacity-75-hover">
              {% include "_logo.html" %}
            </a>
          </section>

          <section class="d-none d-lg-block">
            {% include "_navmenu.html" %}
          </section>

          <section class="dropdown">
            <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-person"></i>
            </button>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Meu Perfil</a></li>
              <li><a class="dropdown-item" href="#">Minha Empresa</a></li>
              <li><a class="dropdown-item" href="#">Ajuda</a></li>
              <li><form action="{% url "logout" %}" method="post">
                {% csrf_token %}
                <button type="submit" class="dropdown-item">Encessar Sessão</button>
              </form></li>
            </ul>
          </section>
        </div>
      </div>
    </header>

    <aside class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
      <header class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasExampleLabel">Offcanvas</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </header>
      <main class="offcanvas-body">
        {% include "_navmenu.html" %}
      </main>
    </aside>
    {% endblock navmenu %}

    {% block nav-breadcrumb %}
    <div class="container-xxl d-none d-lg-block mb-3">
      <div class="d-flex align-items-center justify-content-between">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            {% block breadcrumb %}
            <li class="breadcrumb-item active" aria-current="page">
              <i class="bi bi-house"></i>
            </li>
            {% endblock breadcrumb %}
          </ol>
        </nav>
        <p>{{ request.user.username }}</p>
      </div>
    </div>
    {% endblock nav-breadcrumb %}

    <main class="container-xxl">
      {% block content %}{% endblock content %}
    </main>
  </body>
</html>

gelias/templates/_logo.html
Grupo <span class="text-primary text-capitalize fw-bold fst-italic">Elias</span>

gelias/templates/_navmenu.html
<nav class="nav nav-underline flex-column flex-lg-row">
  <a
    href="{% url "clientes:index" %}"
    class="text-capitalize {% if pagina == 'clientes' %}link-primary{% else %}link-body-emphasis{% endif %} link-offset-2 link-underline-opacity-25 link-underline-opacity-75-hover"
    {% if pagina == 'clientes' %}aria-current="page"{% endif %}
  >
    clientes
  </a>
  <a
    href=""
    class="text-capitalize {% if pagina == 'manutenção' %}link-primary{% else %}link-body-emphasis{% endif %} link-offset-2 link-underline-opacity-25 link-underline-opacity-75-hover"
    {% if pagina == 'manutenção' %}aria-current="page"{% endif %}
  >
    manutenção
  </a>
  <a
    href=""
    class="text-capitalize {% if pagina == 'orçamentos' %}link-primary{% else %}link-body-emphasis{% endif %} link-offset-2 link-underline-opacity-25 link-underline-opacity-75-hover"
    {% if pagina == 'orçamentos' %}aria-current="page"{% endif %}
  >
    orçamentos
  </a>
  <a
    href=""
    class="text-capitalize {% if pagina == 'estoque' %}link-primary{% else %}link-body-emphasis{% endif %} link-offset-2 link-underline-opacity-25 link-underline-opacity-75-hover"
    {% if pagina == 'estoque' %}aria-current="page"{% endif %}
  >
    estoque
  </a>
</nav>